---
- name: Copy k3s binary
  copy:
    src: "{{ k3s_local_binary }}"
    dest: "{{ k3s_binary_dest }}"
    mode: '0755'

- name: Copy k3s install script
  copy:
    src: "{{ k3s_local_install_script }}"
    dest: "{{ k3s_install_script_dest }}"
    mode: '0755'

- name: Ensure k3s images directory exists
  file:
    path: "{{ k3s_airgap_images_dir }}"
    state: directory
    mode: '0755'

- name: Copy k3s air-gap images
  copy:
    src: "{{ k3s_local_airgap_bundle }}"
    dest: "{{ k3s_airgap_images_dir }}/k3s-airgap-images-arm64.tar.zst"
    mode: '0644'

- name: Copy dnsmasq image
  copy:
    src: /tmp/k3s-images/dnsmasq.tar
    dest: "{{ k3s_airgap_images_dir }}/dnsmasq.tar"
    mode: '0644'

- name: Copy lease-watcher image
  copy:
    src: /tmp/k3s-images/lease-watcher.tar
    dest: "{{ k3s_airgap_images_dir }}/lease-watcher.tar"
    mode: '0644'

- name: Copy ansible-runner image
  copy:
    src: /tmp/k3s-images/ansible-runner.tar
    dest: "{{ k3s_airgap_images_dir }}/ansible-runner.tar"
    mode: '0644'


- name: Copy gitea image tar to server
  ansible.builtin.copy:
    src: /tmp/k3s-images/gitea.tar
    dest: "{{ k3s_airgap_images_dir }}/gitea.tar"
    mode: '0644'


- name: Copy helm binary to server
  ansible.builtin.copy:
    src: /tmp/k3s-images/helm
    dest: /usr/local/bin/helm
    mode: '0755'
  become: true