- name: Copy gitea image
  copy:
    src: /tmp/k3s-images/gitea.tar
    dest: "{{ k3s_airgap_images_dir }}/gitea.tar"
    mode: '0644'

- name: Copy argocd image
  copy:
    src: /tmp/k3s-images/argocd.tar
    dest: "{{ k3s_airgap_images_dir }}/argocd.tar"
    mode: '0644'

- name: Copy redis image
  copy:
    src: /tmp/k3s-images/redis.tar
    dest: "{{ k3s_airgap_images_dir }}/redis.tar"
    mode: '0644'

- name: Copy dex image
  copy:
    src: /tmp/k3s-images/dex.tar
    dest: "{{ k3s_airgap_images_dir }}/dex.tar"
    mode: '0644'

- name: Copy argocd install manifest
  copy:
    src: /tmp/k3s-images/argocd-install.yaml
    dest: "/home/{{ ansible_user }}/argocd-install.yaml"
    mode: '0644'