---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dnsmasq-dhcp
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-joiner
  namespace: kube-system
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dnsmasq-dhcp-node-joiner
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-joiner
subjects:
  - kind: ServiceAccount
    name: dnsmasq-dhcp
    namespace: kube-system
