---
- name: Run k3s agent uninstall script
  shell: /usr/local/bin/k3s-agent-uninstall.sh
  ignore_errors: true

- name: Remove k3s binary
  file:
    path: "{{ k3s_binary_dest }}"
    state: absent

- name: Remove k3s install script
  file:
    path: "{{ k3s_install_script_dest }}"
    state: absent

- name: Remove k3s agent service file
  file:
    path: "{{ k3s_agent_service_file }}"
    state: absent
  ignore_errors: true
  notify: Reload systemd

- name: Remove immutable flag from load balancer config
  shell: chattr -i /var/lib/rancher/k3s/agent/etc/k3s-agent-load-balancer.json 2>/dev/null || true
  ignore_errors: true

- name: Remove k3s data directory
  file:
    path: "{{ k3s_data_dir }}"
    state: absent

- name: Remove rancher config
  file:
    path: /etc/rancher
    state: absent

- name: Remove k3s agent service env file
  file:
    path: "{{ k3s_agent_service_file }}.env"
    state: absent
