apiVersion: v1
kind: ServiceAccount
metadata:
  name: lease-watcher
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lease-watcher
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lease-watcher
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: lease-watcher
    namespace: kube-system
roleRef:
  kind: Role
  name: lease-watcher
  apiGroup: rbac.authorization.k8s.io