apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.tenantName }}-limits
  namespace: {{ .Values.tenantName }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.cpuLimit }}
        memory: {{ .Values.memLimit }}
      defaultRequest:
        cpu: {{ .Values.cpuRequest }}
        memory: {{ .Values.memRequest }}
      max:
        cpu: "1"
        memory: "1Gi"
