---
- name: Deploy platform components
  hosts: "{{ groups['server'][0] }}"
  become: true
  roles:
    - containerd_cleanup
    - platform_configmaps
    - deploy_dnsmasq
    - deploy_ansible_runner
    - deploy_gitea
    - deploy_argocd
    - bootstrap_gitops