---
- name: Uninstall k3s from server
  hosts: server
  become: true
  tasks:
    - name: Uninstall k3s server
      include_role:
        name: k3s_server
        tasks_from: uninstall

- name: Uninstall k3s from workers
  hosts: workers
  become: true
  tasks:
    - name: Uninstall k3s agent
      include_role:
        name: k3s_agent
        tasks_from: uninstall
