apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appName }}
spec:
  limits:
    - type: Container
      max:
        {{- toYaml .Values.limitRange.max | nindent 8 }}
      defaultRequest:
        {{- toYaml .Values.limitRange.defaultRequest | nindent 8 }}
