apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appName }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.cpu }}
    requests.memory: {{ .Values.quota.memory }}
    limits.cpu: {{ .Values.quota.cpu }}
    limits.memory: {{ .Values.quota.memory }}
