apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appName }}
automountServiceAccountToken: false
imagePullSecrets:
  - name: {{ .Values.appName }}-pull
